name: Deploy Produção

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Executar deploy em produção
        run: |
          echo "Iniciando deploy de produção"
          ssh -o StrictHostKeyChecking=no univates@177.44.248.81 \
            "cd /home/univates/prod && chmod +x ./deploy.sh && ./deploy.sh"
          echo "Deploy produção concluído"