name: Testes Laravel

on:
  pull_request:
    branches:
      - homolog

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: tarefa_user
          POSTGRES_PASSWORD: senha123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U tarefa_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # essas VARS vão sobrescrever o .env na hora de rodar artisan
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: test_db
      DB_USERNAME: tarefa_user
      DB_PASSWORD: senha123

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_pgsql, pgsql, zip
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist

      - name: Copiar .env
        run: cp .env.example .env

      - name: Gerar APP_KEY
        run: php artisan key:generate --force

      - name: Executar migrations
        run: php artisan migrate --force

      - name: Run PHPUnit
        env:
          DB_CONNECTION: pgsql
          DB_HOST:     localhost
          DB_PORT:     5432
          DB_DATABASE: test_db
          DB_USERNAME: tarefa_user
          DB_PASSWORD: senha123
        run: php artisan test --no-interaction